remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  
title: Sabrina Xu
#logo: /Users/xushimin/Desktopdescription: Research Portfolio
show_downloads: true
theme: jekyll-theme-minimal

